server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

---
spring:
  config:
    activate:
      on-profile: docker # Docker profile just in case, although there is no docker specific configuration for now.