services:

  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 10

  discovery-service:
    build: discovery
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8761:8761

  gateway:
    build: gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8080:8080
    depends_on:
      discovery-service:
        condition: service_started

  movie-service:
    build: movie
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      discovery-service:
        condition: service_started

  user-service:
    build: user
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      discovery-service:
        condition: service_started

  watchlist-service:
    build: watch-list
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      discovery-service:
        condition: service_started

  front:
    build: front
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      movie-service:
        condition: service_started
      user-service:
        condition: service_started
      watchlist-service:
        condition: service_started
      rabbitmq:
        condition: service_healthy
      discovery-service:
        condition: service_started