services:

  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 10s
      timeout: 5s
      retries: 10

  config-server:
    build: configuration

  discovery-service:
    build: discovery
    ports:
      - 8761:8761
    depends_on:
      - config-server

  gateway:
    build: gateway
    ports:
      - 8080:8080
    depends_on:
      - config-server
      - discovery-service

  movie-service:
    build: movie
    depends_on:
      - db
      - rabbitmq
      - discovery-service
      - config-server

  user-service:
    build: user
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - db
      - rabbitmq
      - discovery-service
      - config-server

  watchlist-service:
    build: watch-list
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - db
      - rabbitmq
      - discovery-service
      - config-server

  front:
    build: front
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - movie-service
      - user-service
      - watchlist-service
      - rabbitmq
      - discovery-service
      - config-server